[package]
name = "bevy_registration"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace]
members = ["procedural_macros"]

[dependencies]
procedural_macros = {path="procedural_macros"}
bevy = { version = "0.15.1", default-features = false }
inventory = "0.3.16"