[package]
name = "procedural_macros"
edition = "2024"
# I do not know why we need 2 versions. Why would they ever be different?
# Doesn't work without this version though. Weird.
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.77"
quote = "1.0.37"
proc-macro2 = "1.0.86"